<?php

use yii\db\Migration;

/**
 * Class m181222_234821_Insert_country_data
 */
class m181222_234821_Insert_country_data extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function up()
    {
        Yii::$app->db->createCommand("
            INSERT INTO `country` (`id`, `abbr`, `name`, `long_name`, `phone_code`, `is_active`) VALUES
                (1, 'AF', 'Afghanistan', 'Islamic Republic of Afghanistan', '93', 1),
                (2, 'AX', 'Aland Islands', '&Aring;land Islands', '358', 1),
                (3, 'AL', 'Albania', 'Republic of Albania', '355', 1),
                (4, 'DZ', 'Algeria', 'People''s Democratic Republic of Algeria', '213', 1),
                (5, 'AS', 'American Samoa', 'American Samoa', '1+684', 1),
                (6, 'AD', 'Andorra', 'Principality of Andorra', '376', 1),
                (7, 'AO', 'Angola', 'Republic of Angola', '244', 1),
                (8, 'AI', 'Anguilla', 'Anguilla', '1+264', 1),
                (9, 'AQ', 'Antarctica', 'Antarctica', '672', 1),
                (10, 'AG', 'Antigua and Barbuda', 'Antigua and Barbuda', '1+268', 1),
                (11, 'AR', 'Argentina', 'Argentine Republic', '54', 1),
                (12, 'AM', 'Armenia', 'Republic of Armenia', '374', 1),
                (13, 'AW', 'Aruba', 'Aruba', '297', 1),
                (14, 'AU', 'Australia', 'Commonwealth of Australia', '61', 1),
                (15, 'AT', 'Austria', 'Republic of Austria', '43', 1),
                (16, 'AZ', 'Azerbaijan', 'Republic of Azerbaijan', '994', 1),
                (17, 'BS', 'Bahamas', 'Commonwealth of The Bahamas', '1+242', 1),
                (18, 'BH', 'Bahrain', 'Kingdom of Bahrain', '973', 1),
                (19, 'BD', 'Bangladesh', 'People''s Republic of Bangladesh', '880', 1),
                (20, 'BB', 'Barbados', 'Barbados', '1+246', 1),
                (21, 'BY', 'Belarus', 'Republic of Belarus', '375', 1),
                (22, 'BE', 'Belgium', 'Kingdom of Belgium', '32', 1),
                (23, 'BZ', 'Belize', 'Belize', '501', 1),
                (24, 'BJ', 'Benin', 'Republic of Benin', '229', 1),
                (25, 'BM', 'Bermuda', 'Bermuda Islands', '1+441', 1),
                (26, 'BT', 'Bhutan', 'Kingdom of Bhutan', '975', 1),
                (27, 'BO', 'Bolivia', 'Plurinational State of Bolivia', '591', 1),
                (28, 'BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', '599', 1),
                (29, 'BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', '387', 1),
                (30, 'BW', 'Botswana', 'Republic of Botswana', '267', 1),
                (31, 'BV', 'Bouvet Island', 'Bouvet Island', 'NONE', 1),
                (32, 'BR', 'Brazil', 'Federative Republic of Brazil', '55', 1),
                (33, 'IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory', '246', 1),
                (34, 'BN', 'Brunei', 'Brunei Darussalam', '673', 1),
                (35, 'BG', 'Bulgaria', 'Republic of Bulgaria', '359', 1),
                (36, 'BF', 'Burkina Faso', 'Burkina Faso', '226', 1),
                (37, 'BI', 'Burundi', 'Republic of Burundi', '257', 1),
                (38, 'KH', 'Cambodia', 'Kingdom of Cambodia', '855', 1),
                (39, 'CM', 'Cameroon', 'Republic of Cameroon', '237', 1),
                (40, 'CA', 'Canada', 'Canada', '1', 1),
                (41, 'CV', 'Cape Verde', 'Republic of Cape Verde', '238', 1),
                (42, 'KY', 'Cayman Islands', 'The Cayman Islands', '1+345', 1),
                (43, 'CF', 'Central African Republic', 'Central African Republic', '236', 1),
                (44, 'TD', 'Chad', 'Republic of Chad', '235', 1),
                (45, 'CL', 'Chile', 'Republic of Chile', '56', 1),
                (46, 'CN', 'China', 'People''s Republic of China', '86', 1),
                (47, 'CX', 'Christmas Island', 'Christmas Island', '61', 1),
                (48, 'CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', '61', 1),
                (49, 'CO', 'Colombia', 'Republic of Colombia', '57', 1),
                (50, 'KM', 'Comoros', 'Union of the Comoros', '269', 1),
                (51, 'CG', 'Congo', 'Republic of the Congo', '242', 1),
                (52, 'CK', 'Cook Islands', 'Cook Islands', '682', 1),
                (53, 'CR', 'Costa Rica', 'Republic of Costa Rica', '506', 1),
                (54, 'CI', 'Cote d''ivoire (Ivory Coast)', 'Republic of C&ocirc;te D''Ivoire (Ivory Coast)', '225', 1),
                (55, 'HR', 'Croatia', 'Republic of Croatia', '385', 1),
                (56, 'CU', 'Cuba', 'Republic of Cuba', '53', 1),
                (57, 'CW', 'Curacao', 'Cura&ccedil;ao', '599', 1),
                (58, 'CY', 'Cyprus', 'Republic of Cyprus', '357', 1),
                (59, 'CZ', 'Czech Republic', 'Czech Republic', '420', 1),
                (60, 'CD', 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', '243', 1),
                (61, 'DK', 'Denmark', 'Kingdom of Denmark', '45', 1),
                (62, 'DJ', 'Djibouti', 'Republic of Djibouti', '253', 1),
                (63, 'DM', 'Dominica', 'Commonwealth of Dominica', '1+767', 1),
                (64, 'DO', 'Dominican Republic', 'Dominican Republic', '1+809', 1),
                (65, 'EC', 'Ecuador', 'Republic of Ecuador', '593', 1),
                (66, 'EG', 'Egypt', 'Arab Republic of Egypt', '20', 1),
                (67, 'SV', 'El Salvador', 'Republic of El Salvador', '503', 1),
                (68, 'GQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea', '240', 1),
                (69, 'ER', 'Eritrea', 'State of Eritrea', '291', 1),
                (70, 'EE', 'Estonia', 'Republic of Estonia', '372', 1),
                (71, 'ET', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', '251', 1),
                (72, 'FK', 'Falkland Islands (Malvinas)', 'The Falkland Islands (Malvinas)', '500', 1),
                (73, 'FO', 'Faroe Islands', 'The Faroe Islands', '298', 1),
                (74, 'FJ', 'Fiji', 'Republic of Fiji', '679', 1),
                (75, 'FI', 'Finland', 'Republic of Finland', '358', 1),
                (76, 'FR', 'France', 'French Republic', '33', 1),
                (77, 'GF', 'French Guiana', 'French Guiana', '594', 1),
                (78, 'PF', 'French Polynesia', 'French Polynesia', '689', 1),
                (79, 'TF', 'French Southern Territories', 'French Southern Territories', NULL, 1),
                (80, 'GA', 'Gabon', 'Gabonese Republic', '241', 1),
                (81, 'GM', 'Gambia', 'Republic of The Gambia', '220', 1),
                (82, 'GE', 'Georgia', 'Georgia', '995', 1),
                (83, 'DE', 'Germany', 'Federal Republic of Germany', '49', 1),
                (84, 'GH', 'Ghana', 'Republic of Ghana', '233', 1),
                (85, 'GI', 'Gibraltar', 'Gibraltar', '350', 1),
                (86, 'GR', 'Greece', 'Hellenic Republic', '30', 1),
                (87, 'GL', 'Greenland', 'Greenland', '299', 1),
                (88, 'GD', 'Grenada', 'Grenada', '1+473', 1),
                (89, 'GP', 'Guadaloupe', 'Guadeloupe', '590', 1),
                (90, 'GU', 'Guam', 'Guam', '1+671', 1),
                (91, 'GT', 'Guatemala', 'Republic of Guatemala', '502', 1),
                (92, 'GG', 'Guernsey', 'Guernsey', '44', 1),
                (93, 'GN', 'Guinea', 'Republic of Guinea', '224', 1),
                (94, 'GW', 'Guinea-Bissau', 'Republic of Guinea-Bissau', '245', 1),
                (95, 'GY', 'Guyana', 'Co-operative Republic of Guyana', '592', 1),
                (96, 'HT', 'Haiti', 'Republic of Haiti', '509', 1),
                (97, 'HM', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'NONE', 1),
                (98, 'HN', 'Honduras', 'Republic of Honduras', '504', 1),
                (99, 'HK', 'Hong Kong', 'Hong Kong', '852', 1),
                (100, 'HU', 'Hungary', 'Hungary', '36', 1),
                (101, 'IS', 'Iceland', 'Republic of Iceland', '354', 1),
                (102, 'IN', 'India', 'Republic of India', '91', 1),
                (103, 'ID', 'Indonesia', 'Republic of Indonesia', '62', 1),
                (104, 'IR', 'Iran', 'Islamic Republic of Iran', '98', 1),
                (105, 'IQ', 'Iraq', 'Republic of Iraq', '964', 1),
                (106, 'IE', 'Ireland', 'Ireland', '353', 1),
                (107, 'IM', 'Isle of Man', 'Isle of Man', '44', 1),
                (108, 'IL', 'Israel', 'State of Israel', '972', 1),
                (109, 'IT', 'Italy', 'Italian Republic', '39', 1),
                (110, 'JM', 'Jamaica', 'Jamaica', '1+876', 1),
                (111, 'JP', 'Japan', 'Japan', '81', 1),
                (112, 'JE', 'Jersey', 'The Bailiwick of Jersey', '44', 1),
                (113, 'JO', 'Jordan', 'Hashemite Kingdom of Jordan', '962', 1),
                (114, 'KZ', 'Kazakhstan', 'Republic of Kazakhstan', '7', 1),
                (115, 'KE', 'Kenya', 'Republic of Kenya', '254', 1),
                (116, 'KI', 'Kiribati', 'Republic of Kiribati', '686', 1),
                (117, 'XK', 'Kosovo', 'Republic of Kosovo', '381', 1),
                (118, 'KW', 'Kuwait', 'State of Kuwait', '965', 1),
                (119, 'KG', 'Kyrgyzstan', 'Kyrgyz Republic', '996', 1),
                (120, 'LA', 'Laos', 'Lao People''s Democratic Republic', '856', 1),
                (121, 'LV', 'Latvia', 'Republic of Latvia', '371', 1),
                (122, 'LB', 'Lebanon', 'Republic of Lebanon', '961', 1),
                (123, 'LS', 'Lesotho', 'Kingdom of Lesotho', '266', 1),
                (124, 'LR', 'Liberia', 'Republic of Liberia', '231', 1),
                (125, 'LY', 'Libya', 'Libya', '218', 1),
                (126, 'LI', 'Liechtenstein', 'Principality of Liechtenstein', '423', 1),
                (127, 'LT', 'Lithuania', 'Republic of Lithuania', '370', 1),
                (128, 'LU', 'Luxembourg', 'Grand Duchy of Luxembourg', '352', 1),
                (129, 'MO', 'Macao', 'The Macao Special Administrative Region', '853', 1),
                (130, 'MK', 'Macedonia', 'The Former Yugoslav Republic of Macedonia', '389', 1),
                (131, 'MG', 'Madagascar', 'Republic of Madagascar', '261', 1),
                (132, 'MW', 'Malawi', 'Republic of Malawi', '265', 1),
                (133, 'MY', 'Malaysia', 'Malaysia', '60', 1),
                (134, 'MV', 'Maldives', 'Republic of Maldives', '960', 1),
                (135, 'ML', 'Mali', 'Republic of Mali', '223', 1),
                (136, 'MT', 'Malta', 'Republic of Malta', '356', 1),
                (137, 'MH', 'Marshall Islands', 'Republic of the Marshall Islands', '692', 1),
                (138, 'MQ', 'Martinique', 'Martinique', '596', 1),
                (139, 'MR', 'Mauritania', 'Islamic Republic of Mauritania', '222', 1),
                (140, 'MU', 'Mauritius', 'Republic of Mauritius', '230', 1),
                (141, 'YT', 'Mayotte', 'Mayotte', '262', 1),
                (142, 'MX', 'Mexico', 'United Mexican States', '52', 1),
                (143, 'FM', 'Micronesia', 'Federated States of Micronesia', '691', 1),
                (144, 'MD', 'Moldava', 'Republic of Moldova', '373', 1),
                (145, 'MC', 'Monaco', 'Principality of Monaco', '377', 1),
                (146, 'MN', 'Mongolia', 'Mongolia', '976', 1),
                (147, 'ME', 'Montenegro', 'Montenegro', '382', 1),
                (148, 'MS', 'Montserrat', 'Montserrat', '1+664', 1),
                (149, 'MA', 'Morocco', 'Kingdom of Morocco', '212', 1),
                (150, 'MZ', 'Mozambique', 'Republic of Mozambique', '258', 1),
                (151, 'MM', 'Myanmar (Burma)', 'Republic of the Union of Myanmar', '95', 1),
                (152, 'NA', 'Namibia', 'Republic of Namibia', '264', 1),
                (153, 'NR', 'Nauru', 'Republic of Nauru', '674', 1),
                (154, 'NP', 'Nepal', 'Federal Democratic Republic of Nepal', '977', 1),
                (155, 'NL', 'Netherlands', 'Kingdom of the Netherlands', '31', 1),
                (156, 'NC', 'New Caledonia', 'New Caledonia', '687', 1),
                (157, 'NZ', 'New Zealand', 'New Zealand', '64', 1),
                (158, 'NI', 'Nicaragua', 'Republic of Nicaragua', '505', 1),
                (159, 'NE', 'Niger', 'Republic of Niger', '227', 1),
                (160, 'NG', 'Nigeria', 'Federal Republic of Nigeria', '234', 1),
                (161, 'NU', 'Niue', 'Niue', '683', 1),
                (162, 'NF', 'Norfolk Island', 'Norfolk Island', '672', 1),
                (163, 'KP', 'North Korea', 'Democratic People''s Republic of Korea', '850', 1),
                (164, 'MP', 'Northern Mariana Islands', 'Northern Mariana Islands', '1+670', 1),
                (165, 'NO', 'Norway', 'Kingdom of Norway', '47', 1),
                (166, 'OM', 'Oman', 'Sultanate of Oman', '968', 1),
                (167, 'PK', 'Pakistan', 'Islamic Republic of Pakistan', '92', 1),
                (168, 'PW', 'Palau', 'Republic of Palau', '680', 1),
                (169, 'PS', 'Palestine', 'State of Palestine (or Occupied Palestinian Territory)', '970', 1),
                (170, 'PA', 'Panama', 'Republic of Panama', '507', 1),
                (171, 'PG', 'Papua New Guinea', 'Independent State of Papua New Guinea', '675', 1),
                (172, 'PY', 'Paraguay', 'Republic of Paraguay', '595', 1),
                (173, 'PE', 'Peru', 'Republic of Peru', '51', 1),
                (174, 'PH', 'Phillipines', 'Republic of the Philippines', '63', 1),
                (175, 'PN', 'Pitcairn', 'Pitcairn', 'NONE', 1),
                (176, 'PL', 'Poland', 'Republic of Poland', '48', 1),
                (177, 'PT', 'Portugal', 'Portuguese Republic', '351', 1),
                (178, 'PR', 'Puerto Rico', 'Commonwealth of Puerto Rico', '1+939', 1),
                (179, 'QA', 'Qatar', 'State of Qatar', '974', 1),
                (180, 'RE', 'Reunion', 'R&eacute;union', '262', 1),
                (181, 'RO', 'Romania', 'Romania', '40', 1),
                (182, 'RU', 'Russia', 'Russian Federation', '7', 1),
                (183, 'RW', 'Rwanda', 'Republic of Rwanda', '250', 1),
                (184, 'BL', 'Saint Barthelemy', 'Saint Barth&eacute;lemy', '590', 1),
                (185, 'SH', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', '290', 1),
                (186, 'KN', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', '1+869', 1),
                (187, 'LC', 'Saint Lucia', 'Saint Lucia', '1+758', 1),
                (188, 'MF', 'Saint Martin', 'Saint Martin', '590', 1),
                (189, 'PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', '508', 1),
                (190, 'VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', '1+784', 1),
                (191, 'WS', 'Samoa', 'Independent State of Samoa', '685', 1),
                (192, 'SM', 'San Marino', 'Republic of San Marino', '378', 1),
                (193, 'ST', 'Sao Tome and Principe', 'Democratic Republic of S&atilde;o Tom&eacute; and Pr&iacute;ncipe', '239', 1),
                (194, 'SA', 'Saudi Arabia', 'Kingdom of Saudi Arabia', '966', 1),
                (195, 'SN', 'Senegal', 'Republic of Senegal', '221', 1),
                (196, 'RS', 'Serbia', 'Republic of Serbia', '381', 1),
                (197, 'SC', 'Seychelles', 'Republic of Seychelles', '248', 1),
                (198, 'SL', 'Sierra Leone', 'Republic of Sierra Leone', '232', 1),
                (199, 'SG', 'Singapore', 'Republic of Singapore', '65', 1),
                (200, 'SX', 'Sint Maarten', 'Sint Maarten', '1+721', 1),
                (201, 'SK', 'Slovakia', 'Slovak Republic', '421', 1),
                (202, 'SI', 'Slovenia', 'Republic of Slovenia', '386', 1),
                (203, 'SB', 'Solomon Islands', 'Solomon Islands', '677', 1),
                (204, 'SO', 'Somalia', 'Somali Republic', '252', 1),
                (205, 'ZA', 'South Africa', 'Republic of South Africa', '27', 1),
                (206, 'GS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', '500', 1),
                (207, 'KR', 'South Korea', 'Republic of Korea', '82', 1),
                (208, 'SS', 'South Sudan', 'Republic of South Sudan', '211', 1),
                (209, 'ES', 'Spain', 'Kingdom of Spain', '34', 1),
                (210, 'LK', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', '94', 1),
                (211, 'SD', 'Sudan', 'Republic of the Sudan', '249', 1),
                (212, 'SR', 'Suriname', 'Republic of Suriname', '597', 1),
                (213, 'SJ', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', '47', 1),
                (214, 'SZ', 'Swaziland', 'Kingdom of Swaziland', '268', 1),
                (215, 'SE', 'Sweden', 'Kingdom of Sweden', '46', 1),
                (216, 'CH', 'Switzerland', 'Swiss Confederation', '41', 1),
                (217, 'SY', 'Syria', 'Syrian Arab Republic', '963', 1),
                (218, 'TW', 'Taiwan', 'Republic of China (Taiwan)', '886', 1),
                (219, 'TJ', 'Tajikistan', 'Republic of Tajikistan', '992', 1),
                (220, 'TZ', 'Tanzania', 'United Republic of Tanzania', '255', 1),
                (221, 'TH', 'Thailand', 'Kingdom of Thailand', '66', 1),
                (222, 'TL', 'Timor-Leste (East Timor)', 'Democratic Republic of Timor-Leste', '670', 1),
                (223, 'TG', 'Togo', 'Togolese Republic', '228', 1),
                (224, 'TK', 'Tokelau', 'Tokelau', '690', 1),
                (225, 'TO', 'Tonga', 'Kingdom of Tonga', '676', 1),
                (226, 'TT', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', '1+868', 1),
                (227, 'TN', 'Tunisia', 'Republic of Tunisia', '216', 1),
                (228, 'TR', 'Turkey', 'Republic of Turkey', '90', 1),
                (229, 'TM', 'Turkmenistan', 'Turkmenistan', '993', 1),
                (230, 'TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands', '1+649', 1),
                (231, 'TV', 'Tuvalu', 'Tuvalu', '688', 1),
                (232, 'UG', 'Uganda', 'Republic of Uganda', '256', 1),
                (233, 'UA', 'Ukraine', 'Ukraine', '380', 1),
                (234, 'AE', 'United Arab Emirates', 'United Arab Emirates', '971', 1),
                (235, 'GB', 'United Kingdom', 'United Kingdom of Great Britain and Nothern Ireland', '44', 1),
                (236, 'US', 'United States', 'United States of America', '1', 1),
                (237, 'UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'NONE', 1),
                (238, 'UY', 'Uruguay', 'Eastern Republic of Uruguay', '598', 1),
                (239, 'UZ', 'Uzbekistan', 'Republic of Uzbekistan', '998', 1),
                (240, 'VU', 'Vanuatu', 'Republic of Vanuatu', '678', 1),
                (241, 'VA', 'Vatican City', 'State of the Vatican City', '39', 1),
                (242, 'VE', 'Venezuela', 'Bolivarian Republic of Venezuela', '58', 1),
                (243, 'VN', 'Vietnam', 'Socialist Republic of Vietnam', '84', 1),
                (244, 'VG', 'Virgin Islands, British', 'British Virgin Islands', '1+284', 1),
                (245, 'VI', 'Virgin Islands, US', 'Virgin Islands of the United States', '1+340', 1),
                (246, 'WF', 'Wallis and Futuna', 'Wallis and Futuna', '681', 1),
                (247, 'EH', 'Western Sahara', 'Western Sahara', '212', 1),
                (248, 'YE', 'Yemen', 'Republic of Yemen', '967', 1),
                (249, 'ZM', 'Zambia', 'Republic of Zambia', '260', 1),
                (250, 'ZW', 'Zimbabwe', 'Republic of Zimbabwe', '263', 1);
            "
        )->execute();
    }

    /**
     * {@inheritdoc}
     */
    public function down()
    {
        Yii::$app->db->createCommand("TRUNCATE TABLE country")->execute();
    }
    
}
